/* ClassAttend 2.0 - 100% frontend prototype
 * Data: IndexedDB in this browser. Face embeddings and profile photo stay local to the device.
 * Security note: this is a prototype; frontend-only storage/authentication is not tamper-proof.
 */
(() => {
  'use strict';
  const APP = {name:'ClassAttend',version:'2.0',db:'classattend_db',dbVersion:1,stores:{settings:'settings',students:'students',attendance:'attendance',sessions:'sessions'}};
  const MODEL_URL='https://justadudewhohacks.github.io/face-api.js/models';
  const MATCH_DISTANCE=0.48;
  const VERIFY_SECONDS=30;
  let db;
  let state={route:'home',stream:null,qrUrl:'',session:null,modelsLoaded:false,interval:null};

  const $=(s,p=document)=>p.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
  const formatDate=ts=>new Date(ts).toLocaleString();
  const elapsed=ts=>{const s=Math.max(0,Math.floor((Date.now()-ts)/1000)); if(s<60)return `${s}s ago`; const m=Math.floor(s/60); if(m<60)return `${m}m ${s%60}s ago`; const h=Math.floor(m/60); return `${h}h ${m%60}m ago`;};
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));

  function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(APP.db,APP.dbVersion);req.onupgradeneeded=()=>{const d=req.result; for(const s of Object.values(APP.stores)){if(!d.objectStoreNames.contains(s)){d.createObjectStore(s,{keyPath:'id'})}}};req.onsuccess=()=>{db=req.result;resolve()};req.onerror=()=>reject(req.error)});}
  const tx=(store,mode='readonly')=>db.transaction(store,mode).objectStore(store);
  function put(store,obj){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>resolve(obj);r.onerror=()=>reject(r.error)})}
  function get(store,id){return new Promise((resolve,reject)=>{const r=tx(store).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
  function all(store){return new Promise((resolve,reject)=>{const r=tx(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
  function remove(store,id){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
  async function setting(id, fallback=''){const x=await get('settings',id);return x?x.value:fallback}
  async function setSetting(id,value){return put('settings',{id,value})}
  async function hasTeacherSetup(){return !!await setting('teacherConfigured',false)}
  function route(){const raw=location.hash.replace(/^#/,'')||'home';const [r,q]=raw.split('?');state.route=r;state.query=new URLSearchParams(q||'')}
  function go(r,q=''){location.hash='#'+r+(q?('?'+q):'')}

  function shell(title,content,tools=''){return `<header class="topbar"><div class="inner"><div class="brand">${esc(APP.name)} <small>Frontend-only attendance • ${APP.version}</small></div><div class="actions">${tools}<button class="btn ghost" onclick="App.go('home')">Home</button></div></div></header><main class="container">${content}</main><div class="footer">Data is stored locally in this browser. Camera + Face API features require HTTPS or localhost and an internet connection for model loading.</div>`}
  function setupView(){return shell('Setup',`<section class="hero"><div class="card"><h1>First-time setup</h1><p class="muted">Create the class identity and teacher PIN. This stays on this browser only.</p><div class="grid two"><div><div class="field"><label class="label">Teacher name</label><input id="teacherName" class="input" placeholder="e.g. Mr. Sharma"></div><div class="field"><label class="label">Class / subject</label><input id="className" class="input" placeholder="e.g. BCA 2nd Year • Physics"></div><div class="field"><label class="label">Teacher PIN</label><input id="teacherPin" class="input" type="password" minlength="4" placeholder="4+ digits"></div><button class="btn primary" onclick="App.saveSetup()">Save & continue</button></div><div class="notice"><b>Important:</b> because there is no backend, this PIN is only a local UI lock—not enterprise authentication.</div></div></div></section>`)}

  async function home(){const configured=await hasTeacherSetup();return shell('Home',`<section class="hero"><div class="card"><h1>ClassAttend</h1><p class="muted">QR-first class attendance with one-time student registration and local face verification.</p><div class="grid three" style="margin-top:18px"><div class="card"><h3>Teacher Board</h3><p class="muted small">Display one QR code; students scan it. No teacher camera or face scan.</p><button class="btn primary" onclick="App.openTeacher()">Open Teacher</button></div><div class="card"><h3>Student Registration</h3><p class="muted small">Register ID, name, photo and face embedding once on the student's browser/device.</p><button class="btn" onclick="App.go('register')">Register Student</button></div><div class="card"><h3>Student Check-in</h3><p class="muted small">Open the class QR link; verify the registered face and hold the camera check for 30 seconds.</p><button class="btn" onclick="App.go('student')">Open Student Check-in</button></div></div>${configured?'':'<div class="notice warn" style="margin-top:18px">Teacher setup is not completed on this browser yet.</div>'}</div></section>`)}

  async function saveSetup(){const teacherName=$('#teacherName').value.trim(),className=$('#className').value.trim(),pin=$('#teacherPin').value.trim(); if(!teacherName||!className||pin.length<4){alert('Fill teacher name, class and a 4+ character PIN.');return} await setSetting('teacherName',teacherName);await setSetting('className',className);await setSetting('teacherPin',pin);await setSetting('teacherConfigured',true);go('teacher')}

  async function registerView(){return shell('Register',`<section class="grid two hero"><div class="card"><h2>One-time student registration</h2><p class="muted">The browser stores the student profile locally. Use the same browser/device for future check-ins.</p><div class="field"><label class="label">Student ID</label><input id="studentId" class="input" placeholder="e.g. 24BCA017"></div><div class="field"><label class="label">Full name</label><input id="studentName" class="input" placeholder="Student name"></div><div class="camera-stage"><div class="video-wrap"><video id="regVideo" autoplay muted playsinline></video><div class="video-overlay">Center your face in the frame, remove obstructions and use good light.</div></div><div class="row"><button class="btn primary" onclick="App.startRegistrationCamera()">Start camera</button><button class="btn" onclick="App.captureRegistration()">Capture & register</button></div></div><div id="regStatus" class="notice hide"></div></div><div class="card"><h3>Already registered?</h3><p class="muted">Registration does not need to be repeated every time. The check-in flow only verifies the existing local profile.</p><div class="notice warn">A browser reset, clearing site data, private/incognito mode, or changing device can remove the local profile.</div><hr class="divider"><button class="btn" onclick="App.go('student')">Go to check-in</button></div></section>`)}
  async function startRegistrationCamera(){try{await stopStream();state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});$('#regVideo').srcObject=state.stream;await loadModels();$('#regStatus').className='notice';$('#regStatus').textContent='Camera ready. Capture when face is centered.'}catch(e){showStatus('regStatus','Camera/model error: '+e.message,'error')}}
  async function captureRegistration(){const id=$('#studentId').value.trim(),name=$('#studentName').value.trim(),video=$('#regVideo');if(!id||!name){alert('Student ID and name are required.');return}if(!video.srcObject){await startRegistrationCamera();}if(!state.modelsLoaded){alert('Face models are still loading.');return}const det=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.5})).withFaceLandmarks().withFaceDescriptor();if(!det){showStatus('regStatus','No clear face detected. Try better lighting and look at the camera.','error');return}const descriptor=Array.from(det.descriptor);const photo=captureVideoFrame(video);await put('students',{id,name,photo,descriptor,createdAt:Date.now(),updatedAt:Date.now()});showStatus('regStatus',`Registered ${name} (${id}). This profile is now saved in this browser.`,'success');await stopStream()}

  function captureVideoFrame(video){const c=document.createElement('canvas');c.width=video.videoWidth||640;c.height=video.videoHeight||480;c.getContext('2d').drawImage(video,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.78)}
  async function loadModels(){if(state.modelsLoaded)return;showStatus('regStatus','Loading face models…');await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(MODEL_URL),faceapi.nets.faceLandmark68Net.loadFromUri(MODEL_URL),faceapi.nets.faceRecognitionNet.loadFromUri(MODEL_URL)]);state.modelsLoaded=true}
  function showStatus(id,msg,type=''){const e=$('#'+id);if(!e)return;e.className='notice '+(type||'');e.textContent=msg}
  async function stopStream(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null} }

  async function newSession(){const teacherName=await setting('teacherName','Teacher'),className=await setting('className','Class');const session={id:uid('session'),teacherName,className,createdAt:Date.now(),active:true};await put('sessions',session);state.session=session;await setSetting('activeSessionId',session.id);return session}
  async function currentSession(){const id=await setting('activeSessionId','');if(!id)return null;const s=await get('sessions',id);return s&&s.active?s:null}
  async function teacher(){if(sessionStorage.getItem('teacherAuth')!=='1'){setTimeout(()=>go('teacher-login'),0);return shell('Teacher login',`<section class="hero"><div class="card center"><h2>Teacher access required</h2><p class="muted">Use the local teacher PIN to open the dashboard.</p><button class="btn primary" onclick="App.go('teacher-login')">Teacher login</button></div></section>`)}let s=await currentSession();if(!s)s=await newSession();state.session=s;const rows=await attendanceFor(s.id);const students=await all('students');return shell('Teacher',`<section class="hero"><div class="row between"><div><h1 style="margin:0">Teacher board</h1><p class="muted">${esc(s.className)} • ${esc(s.teacherName)}</p></div><div class="actions"><button class="btn primary" onclick="App.refreshTeacher()">Refresh list</button><button class="btn" onclick="App.newClassSession()">New session</button><button class="btn" onclick="App.exportCSV()">CSV</button><button class="btn" onclick="App.exportPDF()">PDF</button></div></div><div class="grid two" style="margin-top:18px"><div class="card"><div class="row between"><div><h2>Scan this QR</h2><p class="muted small">Students use the same URL shown here. Teacher camera is never requested.</p></div><span class="pill green">LIVE</span></div><div id="qr" class="qr-box"></div><div class="row"><button class="btn" onclick="App.copyStudentLink()">Copy link</button><button class="btn" onclick="App.shareStudentLink()">Share link</button></div><p id="linkText" class="small muted" style="word-break:break-all"></p></div><div class="grid three"><div class="card stat"><span class="muted small">Present</span><span class="big" id="presentCount">${rows.length}</span></div><div class="card stat"><span class="muted small">Registered</span><span class="big">${students.length}</span></div><div class="card stat"><span class="muted small">Session started</span><span class="small">${formatDate(s.createdAt)}</span></div></div></div><div class="card" style="margin-top:18px"><div class="row between"><div><h2>Attendance list</h2><p class="muted small">As students check in, this list grows on the teacher board.</p></div><span class="small muted">Auto-refreshes every 3 seconds</span></div><div id="teacherTable" class="table-wrap" style="margin-top:14px">${renderAttendanceTable(rows)}</div></div></section>`);setTimeout(()=>{renderQR(studentUrlForSession(s.id));startTeacherPolling(s.id)},0)}
  async function attendanceFor(sessionId){const a=await all('attendance');return a.filter(x=>x.sessionId===sessionId).sort((a,b)=>b.time-a.time)}
  function renderAttendanceTable(rows){if(!rows.length)return '<div class="empty">No attendance yet. Students will appear here after successful check-in.</div>';return `<table class="table"><thead><tr><th>#</th><th>Student</th><th>ID</th><th>Checked in</th><th>Last login</th><th>Verified</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td><div class="row"><img class="avatar" src="${r.photo||''}" alt=""> <div><b>${esc(r.name)}</b></div></div></td><td>${esc(r.studentId)}</td><td>${formatDate(r.time)}</td><td>${esc(elapsed(r.time))}</td><td><span class="pill green">Face verified</span></td></tr>`).join('')}</tbody></table>`}
  function studentUrlForSession(sessionId){const base=location.href.split('#')[0];return `${base}#student?session=${encodeURIComponent(sessionId)}`}
  function renderQR(url){const q=$('#qr');if(!q)return;q.innerHTML='';new QRCode(q,{text:url,width:280,height:280,correctLevel:QRCode.CorrectLevel.M});$('#linkText').textContent=url}
  function startTeacherPolling(sessionId){clearInterval(state.interval);state.interval=setInterval(async()=>{if(state.route!=='teacher'){clearInterval(state.interval);return}const rows=await attendanceFor(sessionId);$('#teacherTable').innerHTML=renderAttendanceTable(rows);$('#presentCount').textContent=rows.length},3000)}
  async function refreshTeacher(){renderQR(studentUrlForSession(state.session.id));const rows=await attendanceFor(state.session.id);$('#teacherTable').innerHTML=renderAttendanceTable(rows);$('#presentCount').textContent=rows.length}
  async function newClassSession(){if(!confirm('Start a new attendance session? The old session remains saved.'))return;await newSession();await refreshTeacher()}
  function copyStudentLink(){navigator.clipboard?.writeText(studentUrlForSession(state.session.id)).then(()=>alert('Student link copied.')).catch(()=>alert('Copy is blocked by browser; use Share or copy the URL shown.'))}
  async function shareStudentLink(){const url=studentUrlForSession(state.session.id);if(navigator.share){await navigator.share({title:'ClassAttend check-in',text:'Scan/open for attendance',url})}else copyStudentLink()}

  async function student(){const sessionId=state.query.get('session')||await setting('activeSessionId','');const s=sessionId?await get('sessions',sessionId):null;if(!s||!s.active)return shell('Student',`<section class="hero"><div class="card center"><h2>No active class session</h2><p class="muted">Ask the teacher to display the current QR code.</p><button class="btn" onclick="App.go('home')">Home</button></div></section>`);return shell('Student check-in',`<section class="grid two hero"><div class="card"><h2>Student check-in</h2><p class="muted">${esc(s.className)} • ${formatDate(s.createdAt)}</p><div id="studentState" class="notice">Your saved profile will be checked. You do not need to create a username/password every time.</div><div class="video-wrap" style="margin-top:14px"><video id="studentVideo" autoplay muted playsinline></video><canvas id="faceCanvas" class="hide"></canvas><div id="studentOverlay" class="video-overlay">Camera not started</div></div><div class="row" style="margin-top:12px"><button class="btn primary" onclick="App.startStudentCheckin('${s.id}')">Start 30-sec verification</button><button class="btn" onclick="App.stopStudentCheckin()">Stop camera</button></div><div id="countBox" class="center" style="margin-top:14px"></div></div><div class="card"><h3>How it works</h3><p class="muted small">1. Your browser finds the profile saved during registration.</p><p class="muted small">2. Your live face is compared with that saved face.</p><p class="muted small">3. A 30-second verification window helps reduce quick spoof/check-in attempts.</p><p class="muted small">4. One attendance row is created for this class session; repeated checks do not create duplicates.</p><div id="savedProfile" style="margin-top:18px"></div></div></section>`)}
  async function startStudentCheckin(sessionId){try{await stopStream();const students=await all('students');if(!students.length){showStatus('studentState','No student profile is saved in this browser. Register once first.','error');return}state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});const video=$('#studentVideo');video.srcObject=state.stream;$('#studentOverlay').textContent='Look straight at the camera';await loadModels();const started=Date.now();let verifiedCandidate=null;state.verifyDone=false;state.verifyLoop=true;let remain=VERIFY_SECONDS;$('#countBox').innerHTML=`<div class="countdown" id="countdown">${remain}</div><div class="muted">Keep your face visible and relatively still.</div>`;
      const timer=setInterval(async()=>{if(!state.verifyLoop){clearInterval(timer);return}const det=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.5})).withFaceLandmarks().withFaceDescriptor();if(det){const match=findBestMatch(det.descriptor,students);if(match.distance<=MATCH_DISTANCE){verifiedCandidate=match.student;$('#studentOverlay').textContent=`Face match: ${match.student.name} • ${(match.distance).toFixed(2)}`;$('#studentOverlay').style.background='rgba(22,101,52,.85)'}else{$('#studentOverlay').textContent='Face detected, but it does not match a registered student';$('#studentOverlay').style.background='rgba(127,29,29,.85)'}}else{$('#studentOverlay').textContent='No clear face detected';$('#studentOverlay').style.background='rgba(15,23,42,.78)'}remain=Math.max(0,VERIFY_SECONDS-Math.floor((Date.now()-started)/1000));$('#countdown').textContent=remain;if(remain<=0){clearInterval(timer);state.verifyLoop=false;if(verifiedCandidate){await commitAttendance(sessionId,verifiedCandidate);showStatus('studentState',`Attendance marked for ${verifiedCandidate.name}. You can close this page.`,'success')}else{showStatus('studentState','30 seconds completed, but no valid face match was maintained. Try again with good lighting and your registered device.','error')}await stopStream() }},500);
    }catch(e){showStatus('studentState','Camera/model error: '+e.message,'error')}}
  function findBestMatch(descriptor,students){let best=null,bestDistance=Infinity;for(const s of students){if(!Array.isArray(s.descriptor)||s.descriptor.length!==descriptor.length)continue;const d=faceapi.euclideanDistance(descriptor,s.descriptor);if(d<bestDistance){bestDistance=d;best={student:s,distance:d}}}return best||{student:null,distance:Infinity}}
  async function commitAttendance(sessionId,student){const existing=await all('attendance');const dup=existing.find(x=>x.sessionId===sessionId&&x.studentId===student.id);if(dup)return;await put('attendance',{id:uid('att'),sessionId,studentId:student.id,name:student.name,photo:student.photo,time:Date.now()})}
  async function stopStudentCheckin(){state.verifyLoop=false;await stopStream();const c=$('#countBox');if(c)c.innerHTML='<span class="muted">Camera stopped.</span>'}

  async function exportCSV(){const s=state.session||await currentSession();if(!s)return alert('No active session');const rows=await attendanceFor(s.id);const headers=['Student ID','Name','Checked In','Seconds Ago'];const body=rows.map(r=>[r.studentId,r.name,formatDate(r.time),Math.floor((Date.now()-r.time)/1000)]);const csv=[headers,...body].map(row=>row.map(cell=>`"${String(cell).replace(/"/g,'""')}"`).join(',')).join('\n');downloadBlob(csv,`attendance_${safe(s.className)}_${dateStamp()}.csv`,'text/csv;charset=utf-8');}
  async function exportPDF(){const s=state.session||await currentSession();if(!s)return alert('No active session');const rows=await attendanceFor(s.id);if(!window.jspdf){alert('PDF library did not load.');return}const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'pt',format:'a4'});doc.setFontSize(18);doc.text('ClassAttend Attendance',40,45);doc.setFontSize(10);doc.text(`${s.className} • ${s.teacherName}`,40,64);doc.text(`Session: ${formatDate(s.createdAt)}`,40,80);let y=110;doc.setFontSize(10);doc.text('#',40,y);doc.text('Student ID',65,y);doc.text('Name',150,y);doc.text('Checked in',340,y);y+=18;rows.forEach((r,i)=>{if(y>760){doc.addPage();y=45}doc.text(String(i+1),40,y);doc.text(String(r.studentId).slice(0,20),65,y);doc.text(String(r.name).slice(0,28),150,y);doc.text(formatDate(r.time),340,y);y+=18});doc.save(`attendance_${safe(s.className)}_${dateStamp()}.pdf`)}
  function safe(s){return String(s||'class').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'class'}
  function dateStamp(){return new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')}
  function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

  async function teacherLogin(){const configured=await hasTeacherSetup();if(!configured){go('setup');return}const pin=prompt('Enter teacher PIN');if(pin===null)return;const saved=await setting('teacherPin','');if(pin!==saved){alert('Incorrect PIN.');return}sessionStorage.setItem('teacherAuth','1');go('teacher')}
  async function studentsAdmin(){const configured=await hasTeacherSetup();if(!configured)return go('setup');const students=await all('students');const html=students.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>ID</th><th>Registered</th><th>Action</th></tr></thead><tbody>${students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.id)}</td><td>${formatDate(s.createdAt)}</td><td><button class="btn danger" onclick="App.deleteStudent('${esc(s.id)}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No profiles registered on this browser.</div>';return shell('Students',`<section class="hero"><div class="row between"><div><h2>Local student registry</h2><p class="muted">These profiles are stored only on this browser.</p></div><button class="btn" onclick="App.go('teacher')">Back to teacher</button></div><div class="card" style="margin-top:18px">${html}</div></section>`)}
  async function deleteStudent(id){if(!confirm('Delete this local student profile?'))return;await remove('students',id);await studentsAdmin().then(v=>$('#app').innerHTML=v)}

  async function submitTeacherLogin(){const pin=$('#loginPin').value;const saved=await setting('teacherPin','');if(pin!==saved){alert('Incorrect PIN.');return}sessionStorage.setItem('teacherAuth','1');go('teacher')}
  const App={go,saveSetup,openTeacher:teacherLogin,teacherLogin,submitTeacherLogin,refreshTeacher,newClassSession,copyStudentLink,shareStudentLink,exportCSV,exportPDF,startRegistrationCamera,captureRegistration,startStudentCheckin,stopStudentCheckin,deleteStudent};window.App=App;
  async function render(){route();await stopStream();clearInterval(state.interval);let v;try{if(state.route==='setup')v=setupView();else if(state.route==='register')v=await registerView();else if(state.route==='teacher-login'){const configured=await hasTeacherSetup();v=configured?shell('Teacher login',`<section class="hero"><div class="card" style="max-width:520px;margin:auto"><h2>Teacher login</h2><p class="muted">This PIN only locks the local teacher view on this browser.</p><div class="field"><label class="label">Teacher PIN</label><input id="loginPin" class="input" type="password" placeholder="Enter PIN" onkeydown="if(event.key==='Enter')App.submitTeacherLogin()"></div><button class="btn primary" onclick="App.submitTeacherLogin()">Unlock teacher dashboard</button></div></section>`):setupView();}else if(state.route==='teacher')v=await teacher();else if(state.route==='student')v=await student();else if(state.route==='students')v=await studentsAdmin();else v=await home();$('#app').innerHTML=v}catch(e){console.error(e);$('#app').innerHTML=shell('Error',`<section class="hero"><div class="card"><h2>Something went wrong</h2><p class="muted">${esc(e.message)}</p><button class="btn" onclick="App.go('home')">Home</button></div></section>`)} }
  window.addEventListener('hashchange',render);window.addEventListener('beforeunload',()=>stopStream());
  openDB().then(render).catch(e=>document.body.innerHTML='<div style="padding:30px">IndexedDB is unavailable in this browser.</div>');
})();
